### ISSUE TITLE
KeyError:"totalCount"

### ISSUE THREAD

**Issue by Rexoen** [AimerLee/OnePlusCloudPictureDownloader#2]
听说前段时间OnePlus升级了云服务系统，请问脚本是否已经无法使用？
```bash
Traceback (most recent call last):
  File "download.py", line 211, in <module>
    photo_infos = PhotoInfoCollector(cookies).list_all_photos()
  File "download.py", line 58, in list_all_photos
    photo_nums = int(res_json['totalCount'])
KeyError: 'totalCount'
```

**Comment by Rexoen** [comment]
补充：list_photos函数中`res.content.decode()`输出的内容:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body bgcolor="white">
<h1>400 Bad Request</h1>
<p>Request header or cookie too large.<hr/>Powered by Tengine</body>
</html>
```
